### ISSUE TITLE
Phpunit Conflict in Version 1.0.8

### ISSUE THREAD

**Issue by 5now** [symfony/test-pack#11]
When I'm going to start my test in symfony 5.4 with PHPUnit/PHPUnit.xml 8.2.5 it will crash because in the composer.json
of this package required phpunit = "*".

 PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit\TextUI\TestRunner::doRun() in /var/www/html/current/bin/.phpunit/phpunit-8.2-0/src/TextUI/Command.php:201
Stack trace:
#0 /var/www/html/current/bin/.phpunit/phpunit-8.2-0/src/TextUI/Command.php(160): PHPUnit\TextUI\Command->run(Array, true)
#1 /var/www/html/current/bin/.phpunit/phpunit-8.2-0/phpunit(22): PHPUnit\TextUI\Command::main()
#2 /var/www/html/current/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(429): include('/var/www/html/c...')
#3 /var/www/html/current/bin/phpunit(13): require('/var/www/html/c...')
#4 {main}
  thrown in /var/www/html/current/bin/.phpunit/phpunit-8.2-0/src/TextUI/Command.php on line 201
make: *** [Makefile:304: app-functionaltest] Fehler 255

**Comment by Nek-** [comment]
I can confirm this bug.

## Details about the bug

We were using phpunit 8.5 for our test suite so we have configured the phpunit.xml like this:

```xml

    <PHP>
		<!-- ... -->
        <server name="SYMFONY_PHPUNIT_VERSION" value="8.5" />
    </php>
```

When it came to update the package `symfony/test-pack`, the new release included PHPUnit version `*` (so it installed phpunit 9.x).

When running tests after that, it ends up with this kind of error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit\TextUI\TestRunner::doRun() in /.../api/bin/.phpunit/phpunit-8.5-0/src/TextUI/Command.php:236
Stack trace:
#0 /.../api/bin/.phpunit/phpunit-8.5-0/src/TextUI/Command.php(195): PHPUnit\TextUI\Command->run(Array, true)
symfony/test-pack#1 /.../api/bin/.phpunit/phpunit-8.5-0/phpunit(22): PHPUnit\TextUI\Command::main()
symfony/test-pack#2 /.../api/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(429): include('/Users/maximeve...')
symfony/test-pack#3 /.../api/bin/phpunit(13): require('/Users/maximeve...')
symfony/test-pack#4 {main}
  thrown in /.../api/bin/.phpunit/phpunit-8.5-0/src/TextUI/Command.php on line 236

Fatal error: Uncaught Error: Call to undefined method PHPUnit\TextUI\TestRunner::doRun() in /.../api/bin/.phpunit/phpunit-8.5-0/src/TextUI/Command.php:236
Stack trace:
#0 /.../api/bin/.phpunit/phpunit-8.5-0/src/TextUI/Command.php(195): PHPUnit\TextUI\Command->run(Array, true)
symfony/test-pack#1 /.../api/bin/.phpunit/phpunit-8.5-0/phpunit(22): PHPUnit\TextUI\Command::main()
symfony/test-pack#2 /.../api/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(429): include('/Users/maximeve...')
symfony/test-pack#3 /.../api/bin/phpunit(13): require('/Users/maximeve...')
symfony/test-pack#4 {main}
  thrown in /.../api/bin/.phpunit/phpunit-8.5-0/src/TextUI/Command.php on line 236
```

## How to fix it

You can unpack the pack:

```
composer unpack symfony/test-pack
```

This will add phpunit in the wrong version to your codebase, just set it to the right version, and it's fine.
